on:
  # Trigger the workflow on push to the master branch
  # push:
  #   branches:
  #     - master

  schedule:
    # runs every 15 minutes starting from minute 0 of every hour
    - cron:  '0/15 * * * *'

name: Seb's automated roster update

jobs:
  render:
    name: Update roster
    runs-on: macOS-latest
    # The action itself will push to master. Make sure we don't run in a
    # loop triggering this action by itself
    if: "!contains(github.event.head_commit.message, 'gh-action-seb')"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install necessary packages
        run: |
          install.packages(c("tidyverse", "lubridate", "glue", "janitor"), dependencies = TRUE)
        shell: Rscript {0}
      - name: Run update script
        run: Rscript -e 'source("update_roster.R")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit -am 'gh-action-seb re-build site' || echo "No changes to commit"
          git push origin master || echo "No changes to commit"
